version: "3.7"

services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # Docker
      - ~/.docker:/root/.docker
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history
      # Git config
      - ~/.gitconfig:/root/.gitconfig
      # Kubernetes
      # - ~/.kube:/root/.kube
    environment:
      - TZ=
    # Needed for debugging
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
